
[platformio]
default_envs = nodemcu-32s_128x64_debug

[env]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 9600
lib_ldf_mode = deep+
board_build.filesystem = littlefs
lib_deps =
	miguelbalboa/MFRC522@^1.4.7
	olikraus/U8g2@^2.28.8
	rpolitex/ArduinoNvs@^2.8

[env:nodemcu-32s_128x64_debug]
build_type = debug
build_flags =
	-D SIXTYFOUR
	-D DEBUG
	; -D SPLIT_ENABLED

[env:nodemcu-32s_128x64_release]
build_type = release
build_flags =
	-D SIXTYFOUR
